version: "3.9"
services:
#  app:
#    image: afarid/todo:0.1.0
#    ports:
#      - "8888:8888"
#    restart: always
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"