// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"time"
)

type Todo struct {
	ID          int32
	Name        string
	Description string
	Username    string
	CreatedAt   time.Time
	Deadline    time.Time
}
